Repository unCookk/uncook, pull requests merged in 2025-02, with the labels that each got.

#5 MongoDB 연결(Mongoose)
  app/api/resume/route.ts
  app/api/test/route.ts
  database/connections/dbConnect.ts
  database/models/resume.model.ts
  database/models/test.model.ts
  lib/counter/counter.model.ts
  next.config.ts
  package.json
  tsconfig.json
  types/global.d.ts
  yarn.lock
Labels: feat

#6 sidebar 제작
  app/_components/header/index.tsx
  app/_components/header/logo.tsx
  app/_components/header/nav-logo.tsx
  app/_components/logo/login-form.tsx
  app/_components/logo/logo-nav.tsx
  app/_components/sidebar/app-sidebar.tsx
  app/_components/sidebar/index.tsx
  app/_components/sidebar/login/index.tsx
  app/_components/sidebar/login/login-form.tsx
  app/_components/sidebar/login/logout-button.tsx
  app/_components/sidebar/menu-item/index.tsx
  app/_components/temp-page/index.tsx
  app/archive/layout.tsx
  app/archive/page.tsx
  app/edit/layout.tsx
  app/edit/page.tsx
  app/layout.tsx
  app/member/layout.tsx
  app/member/page.tsx
  app/projects/layout.tsx
  app/projects/page.tsx
  app/ux-kitchen/layout.tsx
  app/ux-kitchen/page.tsx
  components/ui/navigation-menu.tsx
  package.json
  tailwind.config.ts
  utils/get-device-type.ts
  yarn.lock
Labels: feat

#14 README 초안 작성
  README.md
  docs/ux/cocktail-party-effect.md
  docs/ux/resume-split-view.md
  docs/ux/resume-verify-issue.md
Labels: doc

#15 폴더 구조 및 컨벤션 통일 작업
  app/_components/common/.gitkeep
  app/_components/sidebar/login/login-form.tsx
  app/_components/survey/content-elements/question-block.tsx
  app/_components/survey/content-elements/rating.tsx
  app/_components/survey/survey-content.tsx
  app/api/login/index.ts
Labels: chore

#18 README doc 링크 WIKI로 옮기기
  README.md
  docs/.gitkeep
  docs/sidebar.md
  docs/ux/cocktail-party-effect.md
  docs/ux/resume-split-view.md
  docs/ux/resume-verify-issue.md
  utils/get-device-type.ts
Labels: doc
